#!/usr/bin/env bun
/**
 * Generate a Homebrew formula and a Scoop manifest for a published release.
 *
 * These are the install channels that need no JavaScript runtime: both just
 * download the `bun build --compile` binary the release workflow already
 * attaches, so there is no extra build and nothing new to keep in sync beyond
 * the version and the checksums.
 *
 *   bun scripts/gen-packages.ts <version> [--out dist/packages]
 *
 * Checksums are computed from the real release assets, so this must run AFTER
 * the binaries are uploaded. It fails loudly on a missing asset rather than
 * emitting a formula with a wrong or blank sha256 — a formula that installs the
 * wrong bytes is worse than no formula.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const REPO = "jcsoftdev/project-brain";

/** Release asset per platform. Mirrors the build matrix in release.yml. */
const TARGETS = {
  "darwin-arm64": { asset: "project-brain-darwin-arm64", brew: "arm64_sonoma" },
  "linux-x64": { asset: "project-brain-linux-x64", brew: "x86_64_linux" },
  "linux-arm64": { asset: "project-brain-linux-arm64", brew: "aarch64_linux" },
  "windows-x64": { asset: "project-brain-windows-x64.exe", brew: null },
} as const;

type TargetName = keyof typeof TARGETS;

function assetUrl(version: string, asset: string): string {
  return `https://github.com/${REPO}/releases/download/v${version}/${asset}`;
}

/** SHA-256 of a release asset, streamed rather than buffered whole. */
async function sha256(url: string): Promise<string> {
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(new Uint8Array(await res.arrayBuffer()));
  return hasher.digest("hex");
}

function renderFormula(version: string, sums: Record<string, string>): string {
  return `# Generated by scripts/gen-packages.ts — do not edit by hand.
class ProjectBrain < Formula
  desc "Local-first MCP server for codebase knowledge: semantic search plus a call graph"
  homepage "https://github.com/${REPO}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${assetUrl(version, TARGETS["darwin-arm64"].asset)}"
      sha256 "${sums["darwin-arm64"]}"
    end
    # Intel macOS has no published binary — see the build matrix in release.yml.
  end

  on_linux do
    on_intel do
      url "${assetUrl(version, TARGETS["linux-x64"].asset)}"
      sha256 "${sums["linux-x64"]}"
    end
    on_arm do
      url "${assetUrl(version, TARGETS["linux-arm64"].asset)}"
      sha256 "${sums["linux-arm64"]}"
    end
  end

  def install
    bin.install Dir["project-brain-*"].first => "project-brain"
  end

  def caveats
    <<~EOS
      Register the MCP server and install the host skills:
        project-brain setup

      Then, in a project:
        project-brain init
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/project-brain --version")
  end
end
`;
}

function renderScoopManifest(version: string, sums: Record<string, string>): string {
  return `${JSON.stringify(
    {
      version,
      description:
        "Local-first MCP server for codebase knowledge: semantic search plus a call graph",
      homepage: `https://github.com/${REPO}`,
      license: "MIT",
      architecture: {
        "64bit": {
          url: assetUrl(version, TARGETS["windows-x64"].asset),
          hash: sums["windows-x64"],
          bin: [["project-brain-windows-x64.exe", "project-brain"]],
        },
      },
      checkver: { github: `https://github.com/${REPO}` },
      autoupdate: {
        architecture: {
          "64bit": { url: assetUrl("$version", TARGETS["windows-x64"].asset) },
        },
      },
      notes: [
        "Register the MCP server and install the host skills: project-brain setup",
        "Then, in a project: project-brain init",
      ],
    },
    null,
    2
  )}\n`;
}

const [rawVersion] = process.argv.slice(2).filter((a) => !a.startsWith("--"));
if (!rawVersion) {
  console.error("Usage: bun scripts/gen-packages.ts <version> [--out <dir>]");
  process.exit(1);
}
const version = rawVersion.replace(/^v/, "");

const outIdx = process.argv.indexOf("--out");
const outDir = outIdx !== -1 ? process.argv[outIdx + 1] : "dist/packages";

const sums: Record<string, string> = {};
for (const [name, { asset }] of Object.entries(TARGETS) as [TargetName, { asset: string }][]) {
  const url = assetUrl(version, asset);
  process.stderr.write(`  hashing ${asset}… `);
  sums[name] = await sha256(url);
  process.stderr.write(`${sums[name].slice(0, 12)}…\n`);
}

await mkdir(outDir, { recursive: true });
await writeFile(join(outDir, "project-brain.rb"), renderFormula(version, sums), "utf8");
await writeFile(join(outDir, "project-brain.json"), renderScoopManifest(version, sums), "utf8");

console.log(`Wrote ${outDir}/project-brain.rb and ${outDir}/project-brain.json for ${version}`);
console.log(`
Bootstrap the channels (one-time):
  Homebrew — create github.com/${REPO.split("/")[0]}/homebrew-tap and commit
             Formula/project-brain.rb. Users then:
               brew install ${REPO.split("/")[0]}/tap/project-brain
  Scoop    — create a bucket repo and commit bucket/project-brain.json. Users then:
               scoop bucket add <name> <repo-url> && scoop install project-brain`);
